### ISSUE TITLE
✨ feat: 배포

### ISSUE THREAD

**Issue by noeyoes** [MindBook-Likelion/MindBook_Backend#86]
**📍To-do List**

- [x] github action 적용
- [x] aws 인스턴스 및 rds 만들기
- [x] rds 연결
- [x] docker file 만들기
- [x] CORS 설정
